console.log(100);
console.log(500);
console.log(100);
console.log(500);
var bananaPrice = 12;
console.log(bananaPrice);
var monthlySalary = 2500;
console.log(monthlySalary);
var monthlyCost = 1200;
console.log(typeof monthlyCost);
var seenAfter = 21;
console.log(typeof seenAfter);
var personName = "John nash";
console.log(typeof personName);
var bookPrice = 200;
console.log(typeof bookPrice);
var speakerPrice = 5000;
console.log(typeof speakerPrice);
var isRain = true;
var isIce = false;
var isHot = true;
var isRich = false;
var studentNos = 5000;
console.log(typeof studentNos); 
var studentName = "Dipen Chakma";
console.log(typeof studentName);
var isHot = true;
var isRich = false;
console.log(typeof isRich);
var isGood = true;
var isBad = false;
console.log(typeof isBad);
var para = "all that is glitters is not gold";
console.log(para.split('a'));